# Generated by Django 3.2.7 on 2021-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='SOME STRING', upload_to='articles/'),
        ),
    ]
